Fix: Helmet not working properly #4
the-business-of-cities/tboc-site-components pull request #1
Opened 2018-10-16 22:14 UTC by dronsfield

use Head component inside GenericPage and clean up Head nested property errors

2018-10-16 22:19 UTC, mcclowes requested changes

2018-10-16 22:19 UTC, mcclowes commented on src/components/Head/index.js
> +import { path } from "ramda"
```suggestion
import * as R from "ramda"
```

2018-10-16 22:19 UTC, mcclowes commented on src/components/Head/index.js
> +	const image = path(['image', 'url'])(page) || path(['homeImage', 'url'])(site)
```suggestion
	const image = R.path(['image', 'url'])(page) || R.path(['homeImage', 'url'])(site)
```

2018-10-16 22:19 UTC, mcclowes commented on src/components/Head/index.js
> +	const image = path(['image', 'url'])(page) || path(['homeImage', 'url'])(site)
I can see myself getting minorly confused at some future date without the `R.` lol

2018-10-22 15:23 UTC, mcclowes commented
Any thoughts on this @dronsfield?

2018-10-22 15:26 UTC, dronsfield commented
yeah I think it should be changed

2018-10-26 09:16 UTC, merged